import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Prueba tecnica INLAZE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col justify-center w-screen h-screen bg-slate-100 items-center p-24 ${geistSans.variable} ${geistMono.variable} antialiased `}
      >

        {children}
      </body>
    </html>
  );
}
